# _config.yml
title: Jacob Bierstedt
description: Last modified 5-23-2025
author: Jacob Bierstedt
email: jacob.r.bierstedt@gmail.com
baseurl: ""
url: "https://jacobbierstedt.github.io"

theme: minima
google_analytics: G-8EVPE58C2E

markdown: kramdown
plugins:
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num/"

# Permalinks
permalink: /:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
